20220817 ldap service tokens
kanidm/kanidm pull request #1002
Opened 2022-08-24 06:54 UTC by Firstyear

Fixes #990 Fixes #466 Partial #41. This starts to improve our handling of service accounts vs persons, by splitting them better away from the account with sub-person types, rather now having person and service accounts as the top level extended by account properties. This allows them to have seperated and exclusive features. Additionally this also splits the CLI and API to have seperate person and service account end points, with the shared end points being for combined functionality only. 

- [ x ] cargo fmt has been run
- [ ] cargo clippy has been run
- [ x ] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

2022-09-01 03:54 UTC, Firstyear commented
For once I delete more than I add!

2022-09-01 04:12 UTC, yaleman commented
Shenanigans!

2022-09-01 05:09 UTC, yaleman commented on kanidm_book/src/accounts_and_groups.md
> +that will access the system in an interactive way. Service accounts are intentded for use by computers
```suggestion
that will access the system in an interactive way. Service accounts are intended for use by computers
```

2022-09-01 14:12 UTC, yaleman requested changes
Some minor nits on the yak 😄

2022-09-02 03:08 UTC, Firstyear commented on kanidm_book/src/posix_accounts.md
> +    kanidm person|service-account posix show --name anonymous demo_user
Hmmm what would be a better way to say "or"? maybe two lines one for each? Means a lot of duplication though :(

2022-09-02 03:16 UTC, Firstyear commented
Done, comments addressed :)

2022-09-02 04:02 UTC, yaleman approved these changes

2022-09-02 04:21 UTC, merged