20221011 sudo mode
kanidm/kanidm pull request #1120
Opened 2022-10-12 05:06 UTC by Firstyear

partial #1115 adds the "token" components of the sudo/priv mode. This allows an internal field on tokens denoting the purpose or priveleges of the session. Currently we provision all users with read write, but in the future we'll assign them readwrite but expired, and then do a session re-auth to enable "priv" mode. Since these are in the tokens, we enable these for api tokens as well.

- [ x ] cargo fmt has been run
- [ ] cargo clippy has been run
- [ x ] cargo test has been run and passes
- [ x ] book chapter included (if relevant)
- [ ] design document included (if relevant)

2022-10-12 22:45 UTC, yaleman requested changes
Logging locally into my kanidm server's a challenge because journald's choking on my (not that many) endpoints... double-logging denials seems bad 👎🏻

2022-10-12 22:45 UTC, yaleman commented on kanidmd/lib/src/access.rs
> +                security_access!("identity access scope is not permitted to search");
Does this need to be a double log? Why not just 

`"denied ❌ - identity access scope is not permitted to search"`

2022-10-13 00:36 UTC, Firstyear commented
Fixed :)

2022-10-13 00:47 UTC, yaleman approved these changes

2022-10-13 00:54 UTC, merged