Add new scim/sync files
kanidm/kanidm pull request #1152
Opened 2022-10-28 07:44 UTC by Firstyear

Relates #735 #734 #736 #211 . This adds a lot of the foundactions for a "sync account" which will be used to import and drive the process of actually pushing entries from an external IDM to Kanidm. 

- [ x ] cargo fmt has been run
- [ ] cargo clippy has been run
- [ x ] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ x ] design document included (if relevant)

2022-10-28 21:08 UTC, yaleman requested changes
Just that minor naming thing I brought up 👍🏻

2022-10-28 23:04 UTC, Firstyear commented on kanidmd/lib/src/identity.rs
> +    Synch(Uuid),
Sync is a trait / reserved in rust :)

2022-10-28 23:05 UTC, Firstyear commented
I'm also not sure about the name "sync account" as a whole. Like if you were thinking about " ohhh I'm syncing from an external idm into kanidm, what would that be?". Sync Account? Sync Agreement? Sync Connector? Something else? I think it's probably better to change the name sooner than later.

2022-10-28 23:58 UTC, yaleman commented
> I'm also not sure about the name "sync account" as a whole. Like if you were thinking about " ohhh I'm syncing from an external idm into kanidm, what would that be?". Sync Account? Sync Agreement? Sync Connector? Something else? I think it's probably better to change the name sooner than later.

Export/Import? Provisioning? Maybe just call it SCIM since it's a catch-all term (though that can cause its own confusion?)

2022-10-29 06:24 UTC, Firstyear commented
> > I'm also not sure about the name "sync account" as a whole. Like if you were thinking about " ohhh I'm syncing from an external idm into kanidm, what would that be?". Sync Account? Sync Agreement? Sync Connector? Something else? I think it's probably better to change the name sooner than later.
> 
> Export/Import? Provisioning? Maybe just call it SCIM since it's a catch-all term (though that can cause its own confusion?)

But it's not "scim" as a whole, just for "sync" from an external source which happens to use a single part of the scim interface.

I think for now I'll leave it as is since it's not fully complete as a feature yet and not user facing, so we can rename it later.

2022-10-29 08:39 UTC, yaleman approved these changes

2022-10-29 09:07 UTC, merged