WIP: Webauthn-transport
kanidm/kanidm pull request #1204
Opened 2022-11-20 04:02 UTC by micolous

Draft, don't merge yet, needs https://github.com/kanidm/webauthn-rs/pull/215; this PR is on top of #1203 

This uses the `CtapAuthenticator` implementation in `webauthn-authenticator-rs`.  You'll ned to switch to my `transport-auth` branch (https://github.com/kanidm/webauthn-rs/pull/215) to get that working.

Fixes #

- [ ] cargo fmt has been run
- [ ] cargo clippy has been run
- [ ] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

2022-12-14 05:17 UTC, Firstyear commented
@micolous Is there any reason to leave this as WIP? we can merge it and use a dev version of webauthn-rs in this library

2023-07-04 03:55 UTC, Firstyear commented
Is this still needed @micolous ?

2023-07-04 04:46 UTC, micolous commented
Yeah, but I think I'll wait for https://github.com/kanidm/webauthn-rs/pull/324 now

2023-07-12 00:23 UTC, Firstyear requested changes

2023-07-12 00:23 UTC, Firstyear commented on Cargo.toml
> +webauthn-authenticator-rs = { path = "../webauthn-rs/webauthn-authenticator-rs" }
We could point at a git commit instead for now.

2024-08-12 03:57 UTC, Firstyear commented
Closing but we should re-attempt this to remove authenticator-rs.

2024-08-12 03:57 UTC, closed without merging