docs: reformat book and introduce workflow to ensure it stays formatted
kanidm/kanidm pull request #1286
Opened 2022-12-21 14:48 UTC by jceb

- I formatted the book with `deno fmt`
- added syntax name to all preformatted code sections
- extended the kanidm_book github workflow with a test to ensure the documentation stays formatted

2022-12-23 10:45 UTC, yaleman commented
Looks like the changes to the Makefile broke it - can you please check/resolve that?

2022-12-24 05:16 UTC, Firstyear commented
I don't mind this change, I'd prefer column width of 100, but an autoformatter is fine.

I'll trust @yaleman to make the decision on this as they are the github actions wizard.

2022-12-25 09:54 UTC, yaleman requested changes
This needs another rebase and removal of xargs please

2022-12-25 09:54 UTC, yaleman commented on Makefile
> +	find . -type f -name \*.md -print0 | xargs -r -0 deno fmt --check
This doesn't need xargs and the problems that it can bring - `find . -type f -name \*.md -exec deno fmt --check "{}" \;` would do.

2022-12-25 09:56 UTC, yaleman commented
> I don't mind this change, I'd prefer column width of 100, but an autoformatter is fine.
> 
> I'll trust @yaleman to make the decision on this as they are the github actions wizard.

I'm not a *huge* fan of adding another programming language/interpreter to the implicit requirements for the project, but if there's no equivalent in rust-land then it'll do. A standard formatter is nice either way 😃

2022-12-26 03:14 UTC, Firstyear commented
Pretty sure deno is written in rust at least? I thought it was a ts/js engine, didn't know it did formatting.

2022-12-26 08:20 UTC, jceb commented
Yes, it's written in rust.
We could also use https://rome.tools. I haven't used it before but it's also written in rust and focuses on formatting and packaging. A nice addition that we'd get with deno is a JS runtime that could be leveraged for scripting tasks in our CI workflows.

2022-12-26 08:20 UTC, jceb commented
> This needs another rebase and removal of xargs please

Okay, will do.

2022-12-26 08:21 UTC, jceb commented
> I don't mind this change, I'd prefer column width of 100, but an autoformatter is fine.

Okay, will adjust the line length.

2022-12-26 22:51 UTC, yaleman approved these changes
Looks great, thanks 😃

2022-12-26 22:52 UTC, merged