Automatically login & reauth
kanidm/kanidm pull request #1691
Opened 2023-06-03 11:08 UTC by leoleoasd

Discussed in #1690

- [ ] This pr contains no AI generated code
- [ ] cargo fmt has been run
- [ ] cargo clippy has been run
- [ ] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

2023-06-04 11:00 UTC, yaleman requested changes
A few minor changes please, looking good so far!

2023-06-04 11:00 UTC, yaleman commented on tools/cli/src/cli/common.rs
> +                        return Err(ToClientError::Other);
We know the username at this point so this shouldn't be "other"

2023-06-04 11:00 UTC, yaleman commented on tools/cli/src/cli/common.rs
> +                        let login_opt = Select::with_theme(&ColorfulTheme::default())
This should just be a [dialoguer::Confirm](https://docs.rs/dialoguer/0.10.4/dialoguer/struct.Confirm.html)

2023-06-04 11:00 UTC, yaleman commented on tools/cli/src/cli/common.rs
> +                        let login_opt = Select::with_theme(&ColorfulTheme::default())
Same as above, should be a [dialoguer::Confirm](https://docs.rs/dialoguer/0.10.4/dialoguer/struct.Confirm.html)

2023-06-04 23:06 UTC, Firstyear approved these changes
I think this looks really good, it's a good idea and improvement to make things nicer for users. Thanks!

2023-06-05 12:03 UTC, yaleman approved these changes
Awesome, thanks!

2023-06-05 12:03 UTC, merged