Fix debian packaging
kanidm/kanidm pull request #1742
Opened 2023-06-16 08:05 UTC by leoleoasd

Fixes #

- [x] This pr contains no AI generated code
- [ ] cargo fmt has been run
- [ ] cargo clippy has been run
- [ ] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

1. Add prerm according to [document](https://wiki.ubuntu.com/PAMConfigFrameworkSpec):
> Packages implementing PAM profiles under this spec should call pam-auth-update with the --package argument in their postinst script. In the prerm script, these packages should call pam-auth-update --package --remove only when the prerm has been called with remove as its first argument; e.g.:
> ```
> if [ "$1" = remove ]; then
>         pam-auth-update --package --remove unix
> fi
> ```
2. Install pam config manually. I had a misunderstanding on `dh_installpam`. It will install pam configs for the application (such as `/etc/pam.d/sudo`) rather than the system (`/usr/share/pam-configs`).

Decision to be made: Should we automatically enable pam configs during installation? According to the document:
> Packages implementing PAM profiles under this spec should call pam-auth-update with the --package argument in their postinst script.
Will we do anything bad for the system? pam config with a stopped `kanidm-unixd` (since during installation we enable it but there are no working configuration) wouldn't block anything right?

2023-06-16 08:33 UTC, yaleman commented
I always feel a little icky auto-enabling a PAM module like that on install 🤔

2023-06-16 08:56 UTC, Firstyear commented
@micolous You know debian policy better than anyone - Is it acceptable to add a pam/nss module on install? my immediate thinking is "no" from an opensuse background.

2023-06-16 09:21 UTC, leoleoasd commented
It seems that `libpam-sss` (https://debian.pkgs.org/11/debian-main-amd64/sssd-common_2.4.1-2_amd64.deb.html) will automatically enable it's pam in their postinst:

![image](https://github.com/kanidm/kanidm/assets/37735580/4b196465-b7b0-48f3-a010-7b2751387e54)


`pam-auth-update --package` will enable the config if it specifies `Default: yes`:
![image](https://github.com/kanidm/kanidm/assets/37735580/b29af8c3-cb19-4771-8b2e-da3fd4662080)

2023-06-19 06:10 UTC, micolous commented
> @micolous You know debian policy better than anyone - Is it acceptable to add a pam/nss module on install? my immediate thinking is "no" from an opensuse background.

Most Debian packages attempt to build a minimal working config with `dpkg` questions, and start daemons by default on installation.

It looks like the `pam-auth-update` tool and `sssd-common` configs were imported from Ubuntu: https://salsa.debian.org/sssd-team/sssd/-/commit/89e72a82a14d63cdde9ed3a9b87515935962f518

There appears to be an expectation for PAM modules to register themselves _by default_: 

* https://bugs.launchpad.net/ubuntu/+source/pam-pkcs11/+bug/1650366
* https://bugs.launchpad.net/ubuntu/+source/sssd/+bug/557398 
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=568577

> Will we do anything bad for the system? pam config with a stopped kanidm-unixd (since during installation we enable it but there are no working configuration) wouldn't block anything right?

That's one of the questions to answer. It looks like this is all optional, so kanidm not running shouldn't block someone from logging in, or changing their password... and the other thing to answer is to make sure it doesn't allow authenticating with an invalid credential.

2023-06-19 07:05 UTC, Firstyear commented
Provided that other packages have a precedent of doing this, I'm okay with it then :)

2023-06-24 05:31 UTC, Firstyear commented
@yaleman Want to doubl check this?

2023-06-24 06:51 UTC, yaleman requested changes
Command typo, but otherwise let's see how this goes!

2023-06-24 06:51 UTC, yaleman commented on platform/debian/kanidm-unixd/postinst
> +        pan-auth-update --package
```suggestion
        pam-auth-update --package
```

2023-06-24 07:00 UTC, yaleman approved these changes

2023-06-24 08:26 UTC, merged