Resolve issues with dyngroup members
kanidm/kanidm pull request #1986
Opened 2023-08-16 05:08 UTC by Firstyear

Fixes #1942 - I'm not 100% sure of the origin, and I need to dig through the git repos, but we appeard to have duplicated dynmember into member at some point. This caused a failure to start, as dyngroups have a special exemption in refint to avoid checking, but member *does not*. As a result, this caused the server to fail to start.

This adds a "one shot" cleanup of member from dyngroups, adds the needed acp's to allow viewing of dynmembers, a verification to tests that members aren't being added, and a dbscan quarantine command to assist with future debugging and entry isolation when required.

Checklist

- [ x ] This pr contains no AI generated code
- [ x ] cargo fmt has been run
- [ ] cargo clippy has been run
- [ x ] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

2023-08-16 05:47 UTC, yaleman requested changes
nit picked 😄

2023-08-16 05:47 UTC, yaleman commented on server/lib/src/plugins/refint.rs
> +    #[instrument(level = "debug", name = "verify::refint", skip_all)]
shouldn't this be refint::verify ?

2023-08-16 22:02 UTC, Firstyear commented on server/lib/src/plugins/refint.rs
> +    #[instrument(level = "debug", name = "verify::refint", skip_all)]
fixed!

2023-08-17 03:35 UTC, yaleman approved these changes

2023-08-17 05:52 UTC, merged