Add improved domain migration framework and default MFA
kanidm/kanidm pull request #2382
Opened 2023-12-19 06:22 UTC by Firstyear

Fixes #1435 - This upgrades our domain migrations to perform "once off" operations. This way when MFA is enforced it can be undone by admins without the changes being removed.

We can use this in future for other migrations too. 

Checklist

- [ x ] This pr contains no AI generated code
- [ x ] cargo fmt has been run
- [ x ] cargo clippy has been run
- [ x ] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

2023-12-20 09:05 UTC, yaleman requested changes

2023-12-20 09:05 UTC, yaleman commented on server/lib/src/server/migrations.rs
> +        warn!(?db_domain_version);
This should be a debug and say what we're doing
```suggestion
        info!(?db_domain_version, "Before setting internal domain info");
```

2023-12-20 09:05 UTC, yaleman commented on server/lib/src/server/migrations.rs
> +        warn!(?domain_info_version);
This should be a debug and say what we're doing
```suggestion
        info!(?db_domain_version, "After setting internal domain info");
```

2023-12-21 03:35 UTC, Firstyear commented
Added your comments, thanks!

2023-12-21 04:08 UTC, yaleman approved these changes

2023-12-21 04:44 UTC, merged