fix typo
kanidm/kanidm pull request #2908
Opened 2024-07-16 10:04 UTC by alindt

2024-07-16 23:27 UTC, Firstyear approved these changes

2024-07-17 00:50 UTC, yaleman commented on book/src/developers/designs/oauth2_app_listing.md
> +access to the resource server on the kanidm side, while also preserving oauth2 semantics.
```suggestion
access to the resource server on the Kanidm side, while also preserving OAuth2 semantics.
```

2024-07-17 00:50 UTC, yaleman commented on book/src/developers/designs/oauth2_refresh_tokens.md
> +To prevent this, we need oauth2 tokens to "check in" periodically to re-affirm their session
```suggestion
To prevent this, we need OAuth2 tokens to "check in" periodically to re-affirm their session
```

2024-07-17 00:53 UTC, yaleman commented on server/lib/src/filter.rs
> +/// helps to prevent errors at compile time to assert `Filters` are securely. checked
```suggestion
/// helps to prevent errors at compile time to assert `Filters` are securely checked
```

2024-07-17 00:53 UTC, yaleman commented on server/lib/src/macros.rs
> +/// Takes EntryClass objects and makes  a ValueSetIutf8
```suggestion
/// Takes EntryClass objects and makes a ValueSetIutf8
```

2024-07-17 00:56 UTC, yaleman requested changes
Minor nits while we're doing things, but otherwise WOO, thanks! 😄

2024-07-18 03:04 UTC, yaleman approved these changes
Thanks!

2024-07-18 03:22 UTC, merged