Run rust_build CI between multiple Rust versions
kanidm/kanidm pull request #2939
Opened 2024-07-29 08:08 UTC by fossdd

This way, build failures on a upcoming Rust version can be found earlier, and doesn't hold new Kandim releases.

Fixes #

Checklist

- [x] This PR contains no AI generated code
- [x] `cargo fmt` has been run
- [x] `cargo clippy` has been run
- [x] `cargo test` has been run and passes
- [x] book chapter included (if relevant)
- [x] design document included (if relevant)

2024-07-29 10:08 UTC, yaleman commented
As the `rust_build` job is a blocker on merge, I'm not going to support this as-is - nightly/beta versions aren't supported and are inherently going to break things in their own weird ways. 

If this testing is defined as a separate build job that'd work.

2024-07-29 10:08 UTC, yaleman requested changes
See previous comment - not going to merge as-is.

2024-07-29 11:27 UTC, fossdd commented
Oh yeah, didn't know that. Added a new `rust_build_next` job. Let me know if thats fine.

2024-07-29 11:52 UTC, yaleman approved these changes
Thanks

2024-07-30 00:00 UTC, Firstyear approved these changes

2024-07-30 00:08 UTC, merged