20240810 application passwords
kanidm/kanidm pull request #2968
Opened 2024-08-12 07:00 UTC by Firstyear

Supersedes #2578 Fixes #41 

This rebases the PR to latest master, and I'll do the remaining review items. 

Checklist

- [ x ] This PR contains no AI generated code
- [ x ] `cargo fmt` has been run
- [ ] `cargo clippy` has been run
- [ x ] `cargo test` has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

2024-08-14 05:28 UTC, yaleman commented on server/lib/src/constants/groups.rs
> +        name: "idm_ldap_application_admins",
just so it's consistent TBH, can we make sure it matches across similar things like `UUID_IDM_APPLICATION_ADMINS` which doesn't match its group name
```suggestion
    pub static ref BUILTIN_GROUP_LDAP_APPLICATION_ADMINS: BuiltinGroup = BuiltinGroup {
        name: "idm_ldap_application_admins",
```

2024-08-15 07:06 UTC, Firstyear reviewed
Self review notes.

2024-08-15 07:06 UTC, Firstyear commented on server/lib/src/server/delete.rs
> +        if !self.changed_flags.contains(ChangeFlag::APPLICATION)
doubl check

2024-08-15 07:06 UTC, Firstyear commented on server/lib/src/server/mod.rs
> +    fn get_ldap_applications_set(
rename

2024-08-15 07:06 UTC, Firstyear commented on server/lib/src/server/modify.rs
> +
double check

2024-08-16 06:16 UTC, Firstyear commented
This also fixes all the clippy lints. After this, we should make it a hard requirement.

2024-08-20 05:58 UTC, yaleman requested changes

2024-08-20 05:58 UTC, yaleman commented on server/lib/src/idm/event.rs
> +}
Shouldn't this just be a `new` ?

```suggestion
impl LdapApplicationAuthEvent {
    pub fn new(
        app_name: impl ToString,
        usr_uuid: Uuid,
        cleartext: String,
    ) -> Result<Self, OperationError> {
        Ok(LdapApplicationAuthEvent {
            application: app_name.to_string(),
            target: usr_uuid,
            cleartext,
        })
    }
}
```

2024-08-20 06:24 UTC, yaleman commented on proto/src/internal/error.rs
> +            Self::UI0001ChallengeSerialisation => Some("The webauthn challenge was unable to be serialised."),
```suggestion
            Self::UI0001ChallengeSerialisation => Some("The WebAuthn challenge was unable to be serialised."),
```

2024-08-20 06:25 UTC, yaleman approved these changes

2024-08-20 06:44 UTC, merged