Doc format, add api-token section
kanidm/kanidm pull request #2975
Opened 2024-08-15 03:06 UTC by Firstyear

Fixes #2971 - doc how the api token works, run doc/format/fix. 

Checklist

- [ x ] This PR contains no AI generated code
- [ x ] `cargo fmt` has been run
- [ ] `cargo clippy` has been run
- [ ] `cargo test` has been run and passes
- [ x ] book chapter included (if relevant)
- [ ] design document included (if relevant)

2024-08-15 12:02 UTC, yaleman commented on book/src/developers/designs/profile_display.md
> +- email address In the future:
```suggestion
 - email address 

In the future:

```

2024-08-15 12:03 UTC, yaleman commented on book/src/developers/designs/profile_display.md
>  Ssh public key entries in kanidm consist of a:
```suggestion
Ssh public key entries in Kanidm consist of a:
```

2024-08-15 12:04 UTC, yaleman commented on book/src/developers/designs/profile_display.md
> +same. // TODO: Should a user be allowed to relabel their kanidm ssh keys ?
This TODO probably shouldn't be here 😄

2024-08-15 12:04 UTC, yaleman commented on book/src/developers/designs/profile_display.md
> +When editing keys users must be able to add keys, remove keys and update individual key values Each
```suggestion
When editing keys users must be able to add keys, remove keys and update individual key values. Each
```

2024-08-15 12:05 UTC, yaleman commented on book/src/developers/designs/profile_display.md
> +To keep things oranised each category will be their own page with a subnavigation bar to navigate
```suggestion
To keep things organised, each category will be their own page with a sub-navigation bar to navigate
```

2024-08-15 12:06 UTC, yaleman commented on book/src/developers/designs/profile_display.md
>  indow.onload = function () {
```suggestion
window.onload = function () {
```

2024-08-15 12:08 UTC, yaleman commented on book/src/domain_rename.md
> +> This WILL break ALL u2f/webauthn tokens that have been enrolled, which MAY cause accounts to be
```suggestion
> This WILL break ALL U2F/WebAuthn tokens that have been enrolled, which MAY cause accounts to be
```

2024-08-15 12:13 UTC, yaleman requested changes
see comments 😄

2024-08-16 00:12 UTC, Firstyear commented on book/src/domain_rename.md
> +> This WILL break ALL u2f/webauthn tokens that have been enrolled, which MAY cause accounts to be
I have WebAuthn as a formatting so much.

2024-08-17 11:21 UTC, yaleman approved these changes

2024-08-17 11:38 UTC, merged