[htmx] basic profile updating
kanidm/kanidm pull request #2994
Opened 2024-08-23 00:55 UTC by ToxicMushroom

Non access control, non scim (mostly hardcoded data) version

I'm not very happy with how I handled the optional email field atm.

Fixes #

- [x] This PR contains no AI generated code
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

2024-08-23 07:05 UTC, Firstyear commented on server/core/src/https/views/profile.rs
> +            account_name: uat.name().to_string(),
At this point we could probably do a call to get the entry, then you can use the https://github.com/kanidm/kanidm/blob/master/server/lib/src/entry.rs#L2605 apis here to get the exact type and value you need. account_name is "iname", displayName and legalname is utf8, and for mail we might need to return something structured for you so you can handle the primary / not primary case.

2024-12-28 15:04 UTC, johansmitsnl commented
Is this PR gone stale?

2024-12-28 15:54 UTC, ToxicMushroom commented
it is waiting for the scim access control policy feature

2024-12-28 15:57 UTC, johansmitsnl commented
@ToxicMushroom maybe link the issue for others or did I missed it?

2024-12-28 16:10 UTC, ToxicMushroom commented
It does not look explicitly tracked or mentioned anywhere, maybe @Firstyear considers it part of https://github.com/kanidm/kanidm/issues/211. Or otherwise I can create a new issue for it

2024-12-30 01:17 UTC, Firstyear commented
Yeah, create a new issue I need to do this sooner than later. I've just been a bit unwell lately sorry

2025-02-26 04:14 UTC, Firstyear commented
@ToxicMushroom I think this is unblocked for you now with the new scim changes.

2025-03-06 01:31 UTC, ToxicMushroom commented
picking this up again sorry for the delay

2025-03-11 02:31 UTC, Firstyear reviewed
Had a quick play - looks like it needs more work here. I like the unlock feature, maybe it s-hould be a combo "unlock / edit" buton so you have to unlock if you aren't in RW mode, and just gates editing behind some interaction.

Looks like there is no way to save at the end? 

Otherwise, good start.

2025-04-05 01:12 UTC, ToxicMushroom commented
So current todo:
 - fixup the diff ui
 - readd legal name ?  
 - You said something about account name being of type iname, does scim reflect this, is it just a lowercase string ?

2025-04-05 01:27 UTC, ToxicMushroom commented
> Scim can't reflect it, because it doesn't know the rules, I'll have to think about that some more. We may need to have a way to tag attributes with validators.

do we just swipe that under the rug for now and add a // TODO: :p I can create an issue for it too ofcourse

2025-04-05 04:02 UTC, Firstyear commented
Yeah, I think make an issue for it. We need a way to indicate on attributes what validation rules apply. 

Also rebase to master :P

2025-04-10 23:17 UTC, Firstyear requested changes
Needs a rebase, and I need to get that other PR merged.

2025-04-10 23:17 UTC, Firstyear commented on server/core/src/https/views/profile.rs
> +    // TODO: A bit overkill to request scimEffectiveAccess here.
It doesn't cost much, not a huge worry really.

2025-04-10 23:17 UTC, Firstyear commented on server/core/src/https/views/profile.rs
> +            .handle_setattribute(
This should be done in a single modification, not 5 different ones.

2025-04-10 23:17 UTC, Firstyear commented on server/core/src/https/views/profile.rs
> +            .handle_setattribute(
Ahhh https://github.com/kanidm/kanidm/pull/3535 needs me to finish so you can do this in a single scim post.

2025-06-29 15:55 UTC, ToxicMushroom commented on server/core/src/https/views/profile.rs
> +            .handle_setattribute(
I saw the pr got merged but I'm failing to figure out what scim function is relevant for this bulk operation ?

2025-07-01 05:12 UTC, Firstyear commented on server/core/src/https/views/profile.rs
> +            .handle_setattribute(
You want https://github.com/kanidm/kanidm/blob/master/server/lib/src/server/scim.rs#L110

2025-07-02 03:54 UTC, Firstyear commented
Looks great! I think it needs a rebase to resolve the conflicts, but then lets give it a go :)

2025-07-02 17:20 UTC, ToxicMushroom commented on server/lib/src/server/scim.rs
> +        dbg!(&modset);
remove debugging logs

2025-07-02 17:20 UTC, ToxicMushroom commented on server/core/src/https/views/profile.rs
> +    println!("{generic:?}");
remove debugging logs

2025-07-02 17:20 UTC, ToxicMushroom commented on server/core/src/https/views/profile.rs
> +//use crate::https::views::admin::persons::PERSON_ATTRIBUTES;
cleanup

2025-07-02 17:21 UTC, ToxicMushroom commented on server/core/src/actors/v1_scim.rs
> +        println!("{scim_entry_put_event:?}");
remove debugging logs

2025-07-03 23:36 UTC, ToxicMushroom commented
Shoouuld be good now

2025-07-04 03:05 UTC, Firstyear approved these changes
I think there are some rough parts, but it works and the edge cases of mail/username with no permission are all handled safely.

2025-07-04 03:06 UTC, Firstyear approved these changes

2025-07-04 03:15 UTC, merged