SSH Keys page
kanidm/kanidm pull request #3027
Opened 2024-09-08 19:46 UTC by weijiangan

# Change summary

I understand this will eventually be part of update credentials, this is just where I left off
![Screen Shot 2024-09-09 at 03 44 41](https://github.com/user-attachments/assets/7147ccad-7d7e-494b-aa2b-3aaa690ee2a4)

Checklist

- [x] This PR contains no AI generated code
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

2024-09-08 23:46 UTC, yaleman commented
Lookin' good so far!

2024-11-09 01:14 UTC, Firstyear requested changes
This is really out of date with master and needs a rebase, since there has been a lot of work and improvement to the ui side of things recently. I suspect a lot of the pr can be dropped because of that.

2024-11-09 01:14 UTC, Firstyear commented on server/core/Cargo.toml
> +base64 = "0.22"
Should either be from workspace, or more likely, use the serde_as base64 wrappers.

2024-11-09 01:14 UTC, Firstyear commented on server/core/src/https/views/reset.rs
> +struct Aaa {
AAAAAAAAAAAA

2024-12-21 22:17 UTC, weijiangan commented
Sorry it took a while, but I'm back :D @Firstyear

2025-01-07 05:50 UTC, Firstyear reviewed
Code wise this looks good, but I got blocked on https://github.com/kanidm/kanidm/pull/3343 while testing so we need to rebase that in so I can do a last test.

2025-02-06 03:19 UTC, Firstyear commented
@weijiangan Wed love to see this in 1.5 that we plan to release soon, did you have some time to help wrap it up? If not, we can look at it.

2025-02-06 15:53 UTC, weijiangan commented
hey I'll try to wrap it up in these 2 days or I'll let you know to decide on the best course of action

2025-02-06 17:12 UTC, weijiangan commented on server/core/src/https/views/reset.rs
> +        HxResponseTrigger::after_swap([HxEvent::new("addPasswordSwapped".to_string())]);
you're right this is not needed

2025-02-06 17:15 UTC, weijiangan commented on server/core/src/https/views/reset.rs
> +            }
ah, so one adds error texts to the key name field and the other adds to the key body textarea

2025-02-06 18:22 UTC, weijiangan commented
![image](https://github.com/user-attachments/assets/9a1eda0d-66f9-4652-b061-10e288c9c805)

btw I also fixed the navbar styles

2025-02-07 03:49 UTC, Firstyear commented
Hey there, I just rebased your branch, and did a force push along with a fix for an update issue.

Otherwise, I just tested this locally and my lord this is excellent! 

Thank you very much!

2025-02-07 03:50 UTC, Firstyear approved these changes

2025-02-07 03:50 UTC, Firstyear commented on server/core/src/https/views/reset.rs
> +            }
Can we make this a struct (so that the fields are named and clearer to the intent) or can we comment to the purpose of each field inline?

2025-02-08 01:53 UTC, Firstyear approved these changes

2025-02-08 01:54 UTC, merged