20240921 ssh keys
kanidm/kanidm pull request #3056
Opened 2024-09-24 06:17 UTC by Firstyear

# Change summary

- Adds support for unix pw and ssh updates in the credential update session
- In future we will remove the alternate methods to set this so we can unifi account policy here.

Fixes #

Checklist

- [ x ] This PR contains no AI generated code
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

2024-09-24 06:17 UTC, Firstyear commented
I probably need to add book command updates with this ....

2024-10-01 11:01 UTC, yaleman requested changes

2024-10-01 11:01 UTC, yaleman commented on tools/cli/src/cli/person.rs
> +            println!("  unable to modify - account does not have posix attributes");
```suggestion
            println!("  unable to modify - account does not have POSIX attributes");
```

2024-10-01 11:01 UTC, yaleman commented on tools/cli/src/cli/person.rs
> +                    println!("Successfully reset unix password.");
```suggestion
                    println!("Successfully reset UNIX password.");
```

2024-10-01 11:01 UTC, yaleman commented on tools/cli/src/cli/person.rs
> +                    .with_prompt("Do you want to remove your unix password?")
```suggestion
                    .with_prompt("Do you want to remove your UNIX password?")
```

2024-10-01 11:01 UTC, yaleman commented on tools/cli/src/cli/person.rs
> +                    println!("unix password was NOT removed");
```suggestion
                    println!("UNIX password was NOT removed");
```

2024-10-03 03:54 UTC, yaleman approved these changes

2024-10-03 05:41 UTC, yaleman approved these changes

2024-10-03 05:57 UTC, merged