20240925 cleanups
kanidm/kanidm pull request #3060
Opened 2024-09-25 07:03 UTC by Firstyear

# Change summary

- Share the stable serialised formats between repl and db instead of splitting them
- Remove ancient and non-functional older db formats
- Some small pub visibility tidying, more to come here ... 

Fixes #

Checklist

- [ x ] This PR contains no AI generated code
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

2024-09-25 07:04 UTC, Firstyear commented
Note, replication expects matched server versions, so while we are changing the proto, it's *not* a breaking change.

2024-10-01 05:34 UTC, CEbbinghaus approved these changes
now this is a changeset I can get behind
![image](https://github.com/user-attachments/assets/cb8c4107-0e57-450d-955d-e0143217f001)

2024-10-03 02:22 UTC, yaleman requested changes

2024-10-03 02:24 UTC, yaleman approved these changes

2024-10-03 04:04 UTC, yaleman approved these changes

2024-10-03 04:04 UTC, merged