Working scim entry get for person
kanidm/kanidm pull request #3088
Opened 2024-10-04 05:23 UTC by Firstyear

# Change summary

- Add scim person get
- Allow querying to limit the attributes returned

Checklist

- [ x ] This PR contains no AI generated code
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

2024-10-04 05:24 UTC, Firstyear commented
The only place I'm a bit stuck at the moment now is how to actually display and represent the person and the ssh keys.

My thinking is either we can make a nice pretty-printer for ScimEntryGeneric, or we can deserialise into a stronger type for display. Not 100% sure yet.

2024-10-04 06:03 UTC, Firstyear commented
This changes the ssh key list to the same format as today, but using the scim api. I think we need to do a bit of work on the cli in parallel to be ready for scim changes, I'm still just not sure how it should look. Either way, it solves the issue here which is an api to get ssh keys and labels cleanly.

2024-10-05 00:59 UTC, CEbbinghaus requested changes
Am I missing something? Where is the authorised_keys api?

2024-10-05 01:07 UTC, Firstyear commented on proto/src/scim_v1/client.rs
> +use sshkey_attest::proto::PublicKey as SshPublicKey;
PublicKey is ambiguous to other asymmetric public keys.

2024-10-05 01:09 UTC, Firstyear commented
> Am I missing something? Where is the authorised_keys api?

For unixd, the keys are in the UnixUserToken, and then are provided to the caller. For ssh_authorized_keys_direct, it uses idm_account_get_ssh_pubkeys which calls https://github.com/kanidm/kanidm/blob/master/libs/client/src/lib.rs#L2021 instead of SCIM. In future, we should change this to use the SCIM variant.

2024-10-05 01:33 UTC, CEbbinghaus commented
I got that. But both apis currently return json. The related issue asks for a endpoint that recieves the keys in a format compatible with the authorised_keys file. So you could do `curl [api] -o authorised_keys` to remove any post processing

2024-10-05 01:36 UTC, Firstyear commented
"As an aside, it would also be nice to have an API that just returns the authorized_keys file's expected format, without JSON."

it's not the main issue of the ticket. 

Additionally, there can't easily be an api for this as we expect an auth bearer for requests, even for anonymous reqs.

2024-10-05 03:23 UTC, CEbbinghaus approved these changes
LGTM

2024-10-15 03:53 UTC, yaleman submitted a review, later dismissed

2024-10-15 04:25 UTC, yaleman approved these changes

2024-10-15 04:29 UTC, merged