Use specific errors for intent token revoked
kanidm/kanidm pull request #3291
Opened 2024-12-14 02:59 UTC by Firstyear

Rather than the generic 'invalid state' error, we now return proper site-specific errors for credential commit failures, with error messages to explain what went wrong.

Fixes #3288

Checklist

- [x] This PR contains no AI generated code
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

2024-12-14 07:51 UTC, gbw commented on server/lib/src/idm/credupdatesession.rs
>              // TODO: perhaps it would be more helpful to add a new operation error that describes what the issue is
Remove TODO?

2024-12-15 01:01 UTC, CEbbinghaus submitted a review, later dismissed
No additional comments beyond the todo

2024-12-15 20:08 UTC, yaleman requested changes
The security_info log calls at the end could probably be dropped because we have an informative error code but otherwise looks good so far 😊

2024-12-15 20:08 UTC, yaleman commented on proto/src/internal/error.rs
> +            Self::CU0004SessionInconsistent => Some("The session is unable to be committed due to unresolved warnings".into()),
All sentences need to end with appropriate punctuation

2024-12-15 23:52 UTC, Firstyear commented
Applied review feedback.

2024-12-16 00:02 UTC, gbw approved these changes
Good after rebase.

2024-12-16 00:24 UTC, yaleman approved these changes
:uwu:

2024-12-16 00:28 UTC, merged