Ignore system users for UPG synthesiseation
kanidm/kanidm pull request #3297
Opened 2024-12-16 00:37 UTC by Firstyear

Our unix resolver would attempt the right thing to synthesise user private groups on linux as these are an important security boundary. However, it turns out that almost every distro has botched their default system user accounts, and many are installed with numeric-only UPGs that don't resolve. In the case that later the user does attempt to fix that, because we synthesised as UPG for the system account, the user trying to add the UPG would now fail. In some cases this could cause system updates to be prevented from installing.

This change limits UPG synth to user accounts only (uid > 1000) which is the common uid boundary on unix-like platforms.

cc @tacerus 

Checklist

- [x] This PR contains no AI generated code
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

2024-12-16 00:40 UTC, tacerus commented
Thanks for this, should also reduce some of the warnings on startup for system users.

2024-12-16 00:42 UTC, CEbbinghaus approved these changes
Beauty

2024-12-16 00:44 UTC, Firstyear commented
> Thanks for this, should also reduce some of the warnings on startup for system users.

It's a pain because opensuse seems to be particularly bad with botched system user account uid/gid allocations, and I doubt we'll ever be able to fix it.

2024-12-16 02:30 UTC, CEbbinghaus approved these changes
Much prefer this <3

2024-12-16 06:46 UTC, yaleman requested changes
Minor nit

2024-12-16 06:46 UTC, yaleman commented on unix_integration/resolver/src/idprovider/system.rs
> +const SYSTEM_GID_BOUNDARY: u32 = 1000;
Just so it's clear without having to dig into logic

```suggestion
// The minimum GID that Kanidm will consider for creating a UPG
const SYSTEM_GID_BOUNDARY: u32 = 1000;
```

2024-12-17 03:08 UTC, yaleman approved these changes

2024-12-17 03:08 UTC, merged