277 radius not acc pw
kanidm/kanidm pull request #435
Opened 2021-05-06 12:03 UTC by Firstyear

Fixes #277 this prevents the radius password, or variations of it, being used as the main account or unix credential.

- [ x ] cargo fmt has been run
- [ - ] cargo clippy has been run
- [ x ] cargo test has been run and passes
- [ - ] book chapter included (if relevant)
- [ - ] design document included (if relevant)

2021-05-06 12:12 UTC, yaleman commented on kanidmd/src/lib/idm/server.rs
>          // I don't think so - because we should only be showing how STRONG the pw is ...
*I* think so... enumerating passwords is possible if that's a thing :)

2021-05-06 12:21 UTC, yaleman requested changes
Yeah, if the system's going to compare against an existing password and provide feedback to the user that it's invalid (even if it doesn't say that) then ... it's possible to infer a current password, without rate limits. Maybe put *that* check after the "can the user make the change" permission check?

2021-05-07 02:50 UTC, Firstyear commented
Done, it's possible now to do a partial mod application which checks everything "up until" applying to the DB. This means access, schema, plugins are run, then we check the quality, then we finish the application. This avoids the attack method you have noted here.

2021-05-07 03:00 UTC, yaleman approved these changes
Sweet, all checks out from my reading of it. Also - comments explaining the flow are much appreciated as someone Outside Williams Head trying to understand it. :)

2021-05-07 03:01 UTC, merged