minor corrections, line breaks, capitalization, expand abbreviations
kanidm/kanidm pull request #802
Opened 2022-06-01 16:02 UTC by cjschroder

allrightythen, the final Kanidm book review! Like the others this is a light proofread, fixing punctuation, capitalization, spelling, inserting linebreaks to make the source files a little easier to read, and such. Tis a most excellent book for a promising product, you done good!

- [ ] cargo fmt has been run
- [ ] cargo clippy has been run
- [ ] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

2022-06-01 22:11 UTC, yaleman requested changes
Thanks 🥳

2022-06-01 22:11 UTC, yaleman commented on DEVELOPER_README.md
> +<!-- Is this working in the Web UI, instead of on the command line, or working
working *on*, making changes to it etc 😄

2022-06-01 22:11 UTC, yaleman commented on DEVELOPER_README.md
> +You will need [rustup](https://rustup.rs/) to install a rust toolchain. If you're
`Rust` here

2022-06-01 22:11 UTC, yaleman commented on DEVELOPER_README.md
> +Setting different developer profiles while building is done by setting the environment v
Line break broke `variable` here 😄

2022-06-02 05:16 UTC, yaleman commented on DEVELOPER_README.md
> +<!-- Is this working in the Web UI, instead of on the command line, or working
Can confirm, `npm` is no longer needed for WASM building.

2022-06-02 14:57 UTC, cjschroder commented on DEVELOPER_README.md
> +Setting different developer profiles while building is done by setting the environment v
sheesh so picky

2022-06-02 14:59 UTC, cjschroder commented on DEVELOPER_README.md
> +Setting different developer profiles while building is done by setting the environment v
😁

2022-06-02 22:04 UTC, yaleman commented
Woooooooooo, thanks again! 🥳

2022-06-02 22:05 UTC, merged